Sprawdz, czy wszystkie elementy z tablicy A,B i C zwracają wartosc 
logiczna True wzluz osi o indeksie 1.

In [ ]:
import numpy as np


A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
              
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


Sprawdz, czy którykolwiek element z tablic A, B, C i D zwrca wartosc logiczna True


np.any()

In [ ]:
import numpy as np


A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A, B, C, D]):
  print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


Sprawdz, czy którykolwiek element z tablic A, B, C i D zwraca wartosc logiczna True wzluz osi z indeksem 0

In [ ]:
import numpy as np


A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A, B, C, D]):
  print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


Sprawdz macierz A pod katem brakujaych danych np.nan

In [ ]:
import numpy as np


A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


Sprawdz, czy nastepujace tablice A i B sa rowne pod wzgledem elementow okreslonych poziomem tolerancji. Uzyj funkcji np.allclose() z domyslnymi parametrami. 

In [ ]:
import numpy as np


A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

print(np.allclose(A, B))

True


Sprawdz, czy poznisze tablice A i B sa rowne pod wzgledem elementow. Operator porownania ==

In [ ]:
import numpy as np


A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

print(A == B)
# lub 
print(np.equal(A, B))

Sprawdz, Ktore elementy z tablicy A maja wyzsze wartosci niz tablica B. 

In [ ]:
import numpy as np


A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(A > B)

# lub 

print(np.greater(A, B))

[ True False False False]
[ True False False False]


Utworz tablice numpy o ksztalcie 4x4 wypelniona zerami. Ustaw typ danych na int. 

Funkcja np.zeros()

In [ ]:
import numpy as np
print(np.zeros(shape=(4,4), dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Utworz tablice numpy o ksztalcie 10X10 wypelniona 255, Ustaw typ danych na float.
Fukcje np.ones() lub np.full()

In [ ]:
import numpy as np
print(np.full(shape=(10,10), fill_value=255, dtype=float))
# lub 
print('------------------------------------------------')
print(np.ones(shape=(10, 10), dtype='float')  * 255)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
------------------------------------------------
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 25

Zbuduj jednowymiarowa tablice numpy skladajaca sie z wszystkich liczb dwucyfrowaych. 
Funkcja np.arange()

In [ ]:
import numpy as np
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

Zbuduj talice numpy 9 x 10 dla liczby dwucyfrowych. 
Funkcje np.arange() i metody np.ndarray.reshape()

In [ ]:
import numpy as np
a = np.arange(10,100).reshape((9,10))
print(a)

print(np.arange(10,100).reshape(-1,10))

print(np.arange(10,100).reshape(9,-1))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


Zbuduj dwuwymiarowa tablice numpy o ksztalcie 6x6 - macierz jednostkowa o typie danych int

In [ ]:
import numpy as np

print(np.eye(N=6, dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


Ustaw ziarno losowe na 10. Nastepnie zbuduj jednowymiarowa tablice numpy skladajaca sie z 30 pseudolosowych wygenerowanych wartosci z rozkladu jednostajnego na przedziale [0,1). 

In [ ]:
import numpy as np
import random 
np.random.seed(10)
print(np.random.rand(30))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


Ustaw ziarno losowe na 20. Nastepenie zbuduj dwuwymiarowa tablice numpy o ksztalcie (10,4) z wygnererowanymi pseudolosowo wartosciami ze standardowego rozkladu normalnego N(0,1)

In [ ]:
import numpy as np
import random 
np.random.seed(20)

print(np.random.randn(40).reshape((10,4)))

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


Ustaw ziarno losowe na 30. Nasteepnie zbuduj dwuwymiarowa tablice numpy o ksztalcie (10,4) z wygenerowanymi pseoudolosowo wartosciami z rozkładu normalnego N(100,5)

In [ ]:
import numpy as np
import math
np.random.seed(30)

print(math.sqrt(5) * np.random.randn(40).reshape((10,4)) + 100)

[[ 97.17349231 103.41650023  97.82942436 101.05220329]
 [ 99.7748353  100.67930221  96.14063068 103.544381  ]
 [100.30029631  97.52499594 103.52901961 100.24037271]
 [ 98.29153712  98.2666258  103.09437633 101.70027274]
 [ 99.36127721 101.20382627  95.34026547 102.09694365]
 [ 99.98708001  98.95468525  99.05410904 102.38025432]
 [ 93.50787269 103.61547679 103.18753701  98.51356237]
 [102.20256689  96.19764407  97.54000366  97.05813038]
 [101.81233513  97.66380453  98.45883627  98.09317768]
 [102.48979932  95.70413391  98.43161651 101.89861815]]


Dokonaj iteracji po tabllicy numpy A i wydrukuj kazdy element tablicy konsoli.

In [ ]:
import numpy as np

A = np.array([[1,4,3],
              [5,2,6]])
for a in np.nditer(A):
  print(a)

1
4
3
5
2
6


Utworz jednowymiarowa tablice numpy (wektor) skladajacy sie z 11 rowno rozmieszczonych punktow z przedzialu [0,1). 


In [ ]:
import numpy as np

print(np.linspace(start=0,stop=1, num=11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Ustaw ziarno losowe na 42. Wygenruj jednowymiarowa tablice (wektor) zawierajacy mozliwy wynik gry w duzy lotek. 

In [ ]:
import numpy as np

np.random.seed(42)
print(np.random.choice(range(1,50), size=6,replace=False))


[14 46 48 45 18 28]


Zbuduj dwuwymiarowa tablice o ksztalcie 6x6 

In [ ]:
import numpy as np

a = np.zeros((6,6))
b = np.linspace(0,5,6,dtype=int)

print(np.diag(b))

# lub 

print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


Wygeneruj tablice w numpy. Zapisz do pliku binarnego o nazwie 'array.npy', zaladuj ten plik z powrotem do innej zmiennej i wydrukuj zawardtosc do konsoli

In [ ]:
import numpy as np

a = np.arange(12).reshape(3,4)
with open('array.npy', 'wb') as f:
  np.save(f, a)

with open('array.npy', 'rb') as f:
  a = np.load(f)

print(a)

# lub 

np.save('array.npy', a)
b = np.load('array.npy')
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Wygeneruj tablice numpy:
Zapisz tablice do pliku tekstowego o nazwie 'array.txt' z dwoma miejscami po przecinku, zaladuj plik z powrotem do zmiennej i wydrukuj jej zawartosc.

In [ ]:
import numpy as np
a = np.arange(12, dtype=int).reshape(3,4)

np.savetxt('array.txt', a)
b = np.loadtxt('array.txt')

print(b)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


Wygeneruj i przeksztalc nastepujaca tablice numpy:


In [ ]:
import numpy as np

a = np.arange(0,12, dtype=int).reshape(3,4)
print(a)
print(a.tolist())

# lub 

b = np.arange(0,12,dtype=int).reshape(-1,4)
#print(b.tolist())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


Podana jest nastepujaca tablica numpy.
Przeksztalc tablice

In [ ]:
import numpy as np 

a = np.arange(0,12, dtype=int).reshape(3,4).tolist()
print(a)
a = list(reversed(a))
a = np.array(a)
print(a)

# lub 

a = np.arange(0,12, dtype=int).reshape(-1,4)
print(a[::-1])

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


Przekształć  tablice
Funkcja np.pad()


In [ ]:
import numpy as np

a = np.full((4,4),fill_value=1, dtype=float)
print(np.pad(a,(1,1)))

# lub 

A = np.ones(shape=(4, 4))
print(np.pad(A, pad_width=1, constant_values=0))


[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
